micronaut:
  application:
    name: challenge
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ''
netty:
  default:
    allocator:
      max-order: 3

identity-store:
  users:
    rock: rock@1
    juan: juan@2
  roles:
    rock: ROLE_ADMIN
    juan: ROLE_VIEW
